### ISSUE TITLE
[Parse Error] - Bramble Rain Advanced Dualstring Bow

### ISSUE THREAD

**Issue by K1juk** [Kvan7/Exiled-Exchange-2#83] opened 2024-12-17 16:01 UTC
## Parse Error An error occurred while parsing the item
***Bramble Rain
Advanced Dualstring Bow***

### Item Text
***Please provide the item's description***
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message

```
Item Class: Bows
Rarity: Rare
Bramble Rain
Advanced Dualstring Bow
--------
Quality: +20% (augmented)
Physical Damage: 88-163 (augmented)
Elemental Damage: 3-4 (augmented), 2-145 (augmented)
Critical Hit Chance: 7.06% (augmented)
Attacks per Second: 1.20
--------
Requirements:
Level: 55
Dex: 126
--------
Sockets: S S 
--------
Item Level: 76
--------
12% chance to Maim on Hit (enchant)
--------
20% increased Physical Damage (rune)
Adds 1 to 20 Lightning Damage (rune)
--------
Bow Attacks fire an additional Arrow (implicit)
--------
132% increased Physical Damage
Adds 3 to 4 Fire Damage
Adds 1 to 125 Lightning Damage
+2.06% to Critical Hit Chance
Grants 4 Life per Enemy Hit
Gain 5 Life per Enemy Killed
--------
Corrupted

```

**Comment by K1juk** [comment] 2024-12-17 16:02
![Uploading obraz_2024-12-17_170212535.png…]()

**Comment by Kvan7** [comment] 2024-12-17 22:37
duplicate of #60, this will be fixed in the release tonight

**Closed by Kvan7** 2024-12-17 22:37 UTC
Labels: duplicate
