### ISSUE TITLE
[Parse Error] - item name here

### ISSUE THREAD

**Issue by Ali-Khamis** [Kvan7/Exiled-Exchange-2#174] opened 2024-12-25 18:46 UTC
## Parse Error
***Put name of item here, and in the title***

### Item Text
***Please provide the item's description***
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message

```
Please paste it HERE

Item Class: Shields
Rarity: Unique
Arvil's Wheel
Hardwood Targe
--------
Block chance: 35% (augmented)
Armour: 17 (augmented)
Evasion Rating: 12 (augmented)
--------
Sockets: S 
--------
Item Level: 74
--------
42% increased Block chance
67% increased Armour and Evasion
Lose 1% of Life on Kill
Lose 1% of Mana on Kill
33% increased Skill Effect Duration
--------
The unending carnage of war
mercilessly grinds away
at body and mind.

**Comment by Kvan7** [comment] 2024-12-25 18:47
Duplicate of #145

**Closed** 2024-12-25 18:48 UTC
Labels: duplicate, Unique
