### ISSUE TITLE
Cant price check items with any kind of res on them (Query is too complex)

### ISSUE THREAD

**Issue by KlosterR1** [Kvan7/Exiled-Exchange-2#101] opened 2024-12-18 11:23 UTC
## Not Recognized Modifier
***Put name of item here, and in the title***
`Text of the modifier here`

### Item Text
***Please provide the item's description***
```
Item Class: Body Armours
Rarity: Rare
Damnation Pelt
Expert Hexer's Robe
--------
Quality: +20% (augmented)
Energy Shield: 592 (augmented)
--------
Requirements:
Level: 65
Int: 157
--------
Sockets: S S 
--------
Item Level: 72
--------
40% increased Armour, Evasion and Energy Shield (rune)
--------
+50 to maximum Energy Shield
71% increased Energy Shield
+45 to Spirit
+23% to Fire Resistance
+40% to Lightning Resistance
1.6 Life Regeneration per second
```

**Comment by Kvan7** [comment] 2024-12-18 12:05
This item works for me, I need more information/video/screenshots.

**Comment by HenkVanMilligen** [comment] 2024-12-18 12:32
Getting the same for numerous item price checks. Works fine for items with no resistances it seems.
![image](https://github.com/user-attachments/assets/1b0eaa7b-acbe-4810-bdfb-df244b6c8c03)

**Comment by Kvan7** [comment] 2024-12-18 12:33
Please paste the copy text of the item so I can try to reproduce

**Comment by Kvan7** [comment] 2024-12-18 12:33
You can also hit `Browser` to  open the whole query in a browser and manually enable/disable stuff

**Comment by Kvan7** [comment] 2024-12-18 12:35
Again i need the copy text to be able to try and reproduce

**Comment by KlosterR1** [comment] 2024-12-18 12:35
logging into steam in game works for me as well

**Comment by Kvan7** [comment] 2024-12-18 12:38
I have to go to work now, but if you provide the copy-text, press ctrl+c while hovering over an item to copy, I can try and see what the problem is when I get back. 

If it is working again now feel free to close the issue, otherwise I'll look when I get back tonight

**Comment by HenkVanMilligen** [comment] 2024-12-18 12:38
Item Class: Gloves
Rarity: Rare
Sorrow Grasp
Sectioned Bracers
--------
Evasion Rating: 133 (augmented)
--------
Requirements:
Level: 28
Dex: 46
--------
Item Level: 35
--------
+81 to Evasion Rating
Adds 10 to 14 Fire damage to Attacks
+34 to maximum Mana
+16% to Fire Resistance
+17% to Cold Resistance
+6% to Chaos Resistance

**Comment by HenkVanMilligen** [comment] 2024-12-18 12:39
As ocelot suggested, after I logged into the in-game browser (after clicking on the browser button) it started working.

**Comment by Kvan7** [comment] 2024-12-18 12:40
Ok, so it wasn't working but now is after doing authentication. I'll add that to FAQ when I get back. I'm leaving now for real this time :)

**Comment by XcentriXTV** [comment] 2024-12-18 17:20
i get this error but when i try to press browser to login it doesn't do anything at all, just stays on the same screen

**Comment by HenkVanMilligen** [comment] 2024-12-18 17:23
The trade site has been up and down all day. My guess would be the trade site being broken and not the tool.

**Comment by Brasolis** [comment] 2024-12-18 19:17
> You can also hit `Browser` to open the whole query in a browser and manually enable/disable stuff

I don't want to use the built in browser, but it is the only option regardless of if it is enabled/disabled in the settings.

**Comment by jybp** [comment] 2024-12-18 20:23
The latest update broke price checking even a simple one filter check.
 It's not related to the trade site. With 0.1.0 price checking worked fine. I think a revert might be in order.

![image](https://github.com/user-attachments/assets/343526f1-5281-412c-873a-1b62f227ad70)

**Comment by Shinino** [comment] 2024-12-18 21:28
I'm getting this issue, except it isn't even letting me sign in (even though I can sign into the website).

If I open an item and just hit the 'trade' button, it takes me to the site, and loads perfectly fine. If I get the error and hit 'browser', it takes me to a login page, where I simply cannot log in.

Yes, I've verified I'm using the right password.

**Comment by Kvan7** [comment] 2024-12-18 22:13
> The latest update broke price checking even with a simple one filter check. It's not related to the trade site. With 0.1.0 price checking worked fine. I think a revert might be in order.
> 

Looks like the anonymous request trade complexity limit was lowered, meaning that un authenticated requests are more restricted in what they are able to do. You can do one of two things, before selecting "search" hit  "trade"(1) to open in the built in browser and login there, this will mean for the session duration, the normal search will work as before with larger complexities since you are no longer anonymous. Or hit the arrow(2) to open the exact filters in your default browser.

![image](https://github.com/user-attachments/assets/7d12f745-2b4d-456b-9b42-0549bf85276b)

**Comment by Kvan7** [comment] 2024-12-18 22:16
> If you copy-paste it (e.g from password manager), your clipboard will be overwritten by item info. So first u need to open in-app login page, then copy password, back to game, shift-space to open in-app browser again, and paste. Works for me.

You _can_ select to have EE2 restore the clipboard, but I personally wouldn't have this enabled when copy and pasting passwords for obvious reasons. I mean I've looked and it doesn't do anything with the previous clipboard but like, for me there is no reason to have it on since I usually use steam auth to login

**Comment by Thorinori** [comment] 2024-12-19 00:37
There doesn't seem to be a way to log in to the app when it is used in browser mode (so using it within a browser tab vs the overlay), when I hit the browser button there it looks like it tries to open a browser which it then can't since it is already in a browser. The quickest workaround I could think of would be to simply allow us to use either the psuedo mods (which would require the login), or allow us to still use the individual actual mods, or have another way to log in for the app.

**Comment by Kvan7** [comment] 2024-12-19 00:53
That is correct there isn't a way to login when used in browser mode instead of overlay since the program is just electron, your cookies are stored in the default browser then. I'm not implementing extra features at the moment. Use [this prerelease](https://github.com/Kvan7/Exiled-Exchange-2/releases/tag/v0.1.1-cant-auth) if you need the application and can't wait until full pseudo support is added on the trade site. I will not be providing any support for that release since it will not be worked on.

**Comment by Thorinori** [comment] 2024-12-19 02:18
> That is correct there isn't a way to login when used in browser mode instead of overlay since the program is just electron, your cookies are stored in the default browser then. I'm not implementing extra features at the moment. Use [this prerelease](https://github.com/Kvan7/Exiled-Exchange-2/releases/tag/v0.1.1-cant-auth) if you need the application and can't wait until full pseudo support is added on the trade site. I will not be providing any support for that release since it will not be worked on.

Alright, thanks! Any chance at an AppImage release for it as well like the previous releases?

**Comment by Kvan7** [comment] 2024-12-19 02:20
probably not, sorry. I just built it locally, and my local machine is windows. You should be able to build on that tag or zipped source code though to get the correct version

**Closed** 2024-12-19 03:30 UTC
