### ISSUE TITLE
[PoE2] - issue with items in chat

### ISSUE THREAD

**Issue by RelaxTDM** [Kvan7/Exiled-Exchange-2#71] opened 2024-12-15 01:57 UTC
I have found issue, when u try to price check any item in chat modifiers not recodnized, we cant pricecheck any item in chat
![image](https://github.com/user-attachments/assets/ccfcd5cc-bfd8-4f25-ad81-f18eac31a494)
So its not a big problem bcs we now have working price check, but maybe its be fine if this one be worked.

**Comment by RelaxTDM** [comment] 2024-12-15 02:08
![image](https://github.com/user-attachments/assets/b091817d-ecd9-49af-88dd-983d3634eabc)
and also not all modifiers, maybe author write this in patch but idk, just feedback

**Comment by Kvan7** [comment] 2024-12-15 02:14
The second image looks like it is working as intended, noted not an item linked in chat.

The first image, the text of the modifiers is what is actually in the translation game data files. 
![image](https://github.com/user-attachments/assets/1f08b64a-de08-4932-b234-52bd3e877a6f)


Looks like i get the same problem.

**Comment by Kvan7** [comment] 2024-12-15 02:19
this is the text copied to the clipboard:
```
Item Class: Crossbows
Rarity: Rare
Vengeance Core
Bombard Crossbow
--------
[Quality]: +10% (augmented)
[Physical] Damage: 35-103 (augmented)
[ElementalDamage|Elemental] Damage: 3-5 (augmented), 3-52 (augmented)
[Critical|Critical Hit] Chance: 5.00%
Attacks per Second: 1.65
Reload Time: 0.75
--------
Requirements:
Level: 33
[Strength|Str]: 36 (augmented)
[Dexterity|Dex]: 36 (augmented)
--------
Sockets: S S 
--------
Item Level: 36
--------
40% increased [Physical] Damage (rune)
--------
[Grenade] Skills Fire an additional [Projectile|Projectile] (implicit)
--------
Adds 11 to 20 [Physical|Physical] Damage
Adds 3 to 5 [Fire|Fire] Damage
Adds 3 to 52 [Lightning|Lightning] Damage
15% reduced [Attributes|Attribute] Requirements
+13 to [Strength|Strength]
Gain 4 Mana per Enemy Killed
```

**Comment by Kvan7** [comment] 2024-12-15 02:20
This is a PoE 2 bug, in poe1 the text is normal.
Bug report: https://www.pathofexile.com/forum/view-thread/3635338

**Comment by Kvan7** [comment] 2024-12-15 02:22
Feel free to comment, but closing since I don't see a reason to try and implement a workaround for this since GGG will fix it hopefully in a month or so

**Closed by Kvan7** 2024-12-15 02:22 UTC
Labels: upstream: POE2

**Comment by Kvan7** [comment] 2024-12-30 02:16
This has been fixed in latest
