### ISSUE TITLE
CTRL+D Item picture gets stuck to the screen

### ISSUE THREAD

**Issue by Haroldyolo** [Kvan7/Exiled-Exchange-2#152] opened 2024-12-23 11:58 UTC
### Description
CTRL+D Item gets stuck to the screen

### Reproduction steps
Press CTRL+D on an item, the picture gets stuck and you have to either click the pin then X or press CTRL+D on an empty space to clear it. CTRL+ALT+D does not have this issue.

### Screenshot
N/A

**Comment by marcoaaguiar** [comment] 2024-12-23 13:19
It seems a duplicate of #124

**Closed** 2024-12-23 13:21 UTC
