### ISSUE TITLE
[Not Recognized Modifier] - #% increased Physical Damage

### ISSUE THREAD

**Issue by K1juk** [Kvan7/Exiled-Exchange-2#102] opened 2024-12-18 15:36 UTC
## Not Recognized Modifier
***Expert Forge Maul***
`#% increased Physical Damage`

### Item Text
***Please provide the item's description***
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message

```
Item Class: Two Hand Maces
Rarity: Rare
Plague Roar
Expert Forge Maul
--------
Physical Damage: 172-233 (augmented)
Elemental Damage: 16-35 (augmented), 1-33 (augmented)
Critical Hit Chance: 5.00%
Attacks per Second: 1.05
--------
Requirements:
Level: 67
Str: 174 (unmet)
--------
Item Level: 70
--------
54% increased Physical Damage
Adds 16 to 35 Fire Damage
Adds 1 to 33 Lightning Damage
+16% to Critical Damage Bonus
```
Trade site request failed
Error: Unknown stat provided: explicit.stat_419810844

![obraz_2024-12-18_163640540](https://github.com/user-attachments/assets/a8befc3e-ab41-42a3-a60b-a51fe783f373)

**Comment by Kvan7** [comment] 2024-12-18 22:02
duplicate of #82, I will update the title on that one though so it is easier to tell what it is about

**Closed by Kvan7** 2024-12-18 22:02 UTC
Labels: duplicate
